### ISSUE TITLE
Null pointer exception and render problem

### ISSUE THREAD

**Issue by knightcube** [rosenpin/FadingTextView#11]
`java.lang.NullPointerException   at com.tomer.fadingtextview.FadingTextView.startAnimation(FadingTextView.java:269)   at com.tomer.fadingtextview.FadingTextView.resume(FadingTextView.java:59)   at com.tomer.fadingtextview.FadingTextView.onAttachedToWindow(FadingTextView.java:101)`

**Comment by rosenpin** [comment]
Issues aren't a place to shit your logs at.

If you want to help solving the issue, please provide the code you used that caused the crash

**Comment by rosenpin** [comment]
What version of the library are you using?

**Comment by sebamena** [comment]
Me too, last version of lib.

**Comment by rosenpin** [comment]
> Me too, last version of lib.

Could you please provide the code you used in your app to produce this crash?
I couldn't reproduce it

**Comment by sebamena** [comment]
The problem was updating the view dynamically.

My xml look like this:
<com.tomer.fadingtextview.FadingTextView
            android:id="@+id/fadingTextView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

But my app crash, so i have to change my code like this:
<com.tomer.fadingtextview.FadingTextView
            android:id="@+id/fadingTextView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            **app:texts="@array/examples"** />

And the problem gone.

**Lib version: 2.5**

**Comment by rosenpin** [comment]
Is this issue fixed? @sebamena
