### ISSUE TITLE
All texts are not displaying for same period of time. Some faded very fast irrespective of time.

### ISSUE THREAD

**Issue by ThirupathiMukkera** [rosenpin/FadingTextView#13]
List of textviews are not displaying for same period of time. some are fading slowly and some are fast, The last text of the list faded quickly.

**Comment by rosenpin** [comment]
I can't understand exactly what you mean.

Could you send an example code that reproduces this issue?

**Comment by ThirupathiMukkera** [comment]
@Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
//        pause();
//        isShown = false;
    }

  @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
//        resume();
//        isShown = true;
    }



Commented this lines in onAttached and DetachedTo Window. Its working fine
