### ISSUE TITLE
Rename attributes to avoid conflicts

### ISSUE THREAD

**Issue by dzboot02** [rosenpin/FadingTextView#27]
If [Android Leanback](https://developer.android.com/jetpack/androidx/releases/leanback) library is added along side with your project, app build will fail with this error:

Resource compilation failed (Failed to compile values resource file Q:\Projects\Libs\android\fading-text-view\app\build\intermediates\incremental\debug\mergeDebugResources\merged.dir\values\values.xml. Cause: java.nio.file.InvalidPathException: Illegal char <:> at index 59: com.tomerrosenfeld.fadingtextview.app-mergeDebugResources-2:/values/values.xml). Check logs for more details.

This is due to a conflict with a declared style:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <declare-styleable name="FadingTextView">
        <attr name="texts" format="reference" />
        <attr name="timeout" format="integer" />
        <attr name="shuffle" format="boolean" />
    </declare-styleable>
</resources>
```

The problem is with the shuffle attribute, it is already declared in the Leanback library.

**Comment by rosenpin** [comment]
We should rename the attributes to be more specific to avoid conflicts and potential conflicts with other libraries.  
Consider changing to:  
* texts -> fadingTextViewTexts  
* timeout -> fadingTextViewTimeout  
* shuffle -> fadingTextViewShuffle

**Comment by dzboot02** [comment]
Yes, exactly! Thanks.
