### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by LinXiaoTao** [rosenpin/FadingTextView#3]
Hello,
I saw your source, I feel that the effect of using ViewFlipper to do, may be more convenient

**Comment by rosenpin** [comment]
Seems like it could have been easier to implement than my current implementation.
But I can't really see a reason to switch to using ViewFlipper over the current implementation.
Is it more efficient?
Does it use less resources?

**Comment by LinXiaoTao** [comment]
i think since it is designed to achieve a similar function, the performance may be better than our implementation, but I just suggested
