### ISSUE TITLE
setTimeout(JAVA)

### ISSUE THREAD

**Issue by nightcrawlerfemi** [rosenpin/FadingTextView#31]
The setTimeout in java doesn't display and i can't also use the app:timeout on xml, kindly advise

**Comment by nightcrawlerfemi** [comment]
<img width="403" alt="fadetext" src="https://github.com/rosenpin/fading-text-view/assets/73402337/bbf35e25-a2cf-422a-aad2-b29391307266">

**Comment by rosenpin** [comment]
You are trying to use a deprecated method. this is the new function signature:  
https://github.com/rosenpin/fading-text-view/blob/79d89e66926326b3bdc40c3b846996eeaddcc9f4/fadingtextview/src/main/java/com/tomer/fadingtextview/FadingTextView.kt#L198

**Comment by rosenpin** [comment]
Also note that the new function uses Kotlin's Duration object, so if you're using a Java only project you might need to add kotlin to your project
