### ISSUE TITLE
too many animations issue

### ISSUE THREAD

**Issue by hirosz** [rosenpin/FadingTextView#5]
You have startAnimation() in onAttachedToWindow and in handleAttrs() which make animations too fast. In my case it was: first text OK, second much too fast, third OK, fourth many too fast.

**Comment by rosenpin** [comment]
Thanks for letting me know!
Fixed it
To use the updated version:
``` gradle
dependencies {
    compile 'com.tomer:fadingtextview:1.3'
}
```
