### ISSUE TITLE
Animation TimeOut Bug

### ISSUE THREAD

**Issue by kuraydev** [rosenpin/FadingTextView#6]
Hello,
First of all thank you for this easy to use library :)

I found a little bug on your library. When i use fadingTextView.setTimeout(1500) after sometime it just do not wait 1500 ( or whatever i set ) just flick around the array. 

Fortunately, when i set timeout in xml as app:timeout="1500" it did not skip too fast.

I hope you will fix it, when you have time :) 
Enjoy!

**Comment by rosenpin** [comment]
Thanks for letting me know.
I couldn't reproduce the issue on my device.
Are you using the latest version of the library? (1.5)

**Comment by kuraydev** [comment]
Sorry for late response and yes i am using the latest version of the library. If you want i can record a video about that bug.

**Comment by rosenpin** [comment]
I'm not sure what could be the cause of this.
I can't reproduce it on my device.
What android version and device are you using?

**Comment by Moh246810** [comment]
thanks
