### ISSUE TITLE
Simplify input time

### ISSUE THREAD

**Issue by webserveis** [rosenpin/FadingTextView#7]
If you implement TimeUnits

`FTV.setTimeout(1,TimeUnit.SECONDS);`

https://developer.android.com/reference/java/util/concurrent/TimeUnit.html

**Comment by rosenpin** [comment]
What do you think is the problem with the current implementation?

**Comment by webserveis** [comment]
It's just an observation to make the code more consistent.
It is the custom to use libraries to enter units of time, but as it is now it works well too.

**Comment by rosenpin** [comment]
Got it, I'll change it when I have some free time, feel free to open a pull request.
