### ISSUE TITLE
Setting empty text causes crash

### ISSUE THREAD

**Issue by anggrayudi** [rosenpin/FadingTextView#9]
I knew that setting empty text array is not allowed. But, what if we want to set it during runtime only, instead of initially setting it with `app:texts="@array/my_texts"`?

We can show an empty text if the array is empty. Throwing `IllegalArgumentException` directly is not a good action.

**Comment by shofiulla-iota** [comment]
To avoid crashing i have added a static array from string resource in xml and then add dynamic array from java file. I know it's not smart solution but for my case it's working fine.

**Comment by rosenpin** [comment]
The issue with this proposal is that it would be problematic if no static array would be chosen, what would the textview show until you set the text dynamically?
In most cases, the view will render before you get a chance to set the text, what should the default behavior be in this situation? Presenting an empty textview? that could be reasonable if not for the fading animation loop.

If you have an idea for the default behavior for an empty static string array let me know

**Comment by rosenpin** [comment]
There is now a FTV.placeholder built into the library string arrays.  
If you want to leave the FTV empty until you update it at runtime you can use FTV.placeholder.  
If users don't provide any string array, the app will crash with a proper error message 

392f76ae906c302abff6e2296d758a8f1eaa778e
